
services:
  db:
    image: postgres:16-alpine
    container_name: calendar_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calendar_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 20
    networks:
      - private

  api:
    build:
      context: .
    container_name: calendar_server
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/calendar_db
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    networks:
      - private
      - stack-shared

volumes:
  pgdata:

networks:
  private:
    internal: true
  stack-shared:
    external: true
    name: shared_network
